print("hello")
print("GFGGTRFG")
print("C=",10+20)
print("hghusdg")
print("Added lines  to giothub")
print("hello umesh")
print("plz ask sir for attendene sheet")
print("smile now ")
print("u got my msg")
print("Hi,i am Ruchita")